### ISSUE TITLE
Create Instrument value class.

### ISSUE THREAD

**Issue by garretwilson** [salvadore-jefferson/beat_box#5]
Creating parallel arrays of values is error prone and hard to maintain:

    String[] instrumentNames = {"Bass Drum", "Closed Hi-Hat", "Open Hi-Hat", "Acoustic Snare",
      "Crash Cymbal", "Hand Clap", "High Tom", "Hi Bongo", "Maracas", "Whistle", "Low Coga",
      "Cowbell", "Vibraslap", "Low-Mid Tom", "High Agogo", "Open Hi Conga"};
    
    int[] instruments = {35, 42, 46, 38, 49, 39, 50, 60, 70, 72, 64, 56, 58, 47, 67, 63};

It's hard to make sure that you're paring up the correct instrument name with the correct instrument. Plus there's really no way to pass a single instrument to another part of your code.

Create a separate class named `Instrument` to encapsulate the concepts of an instrument name and its identifier.

**Comment by salvadore-jefferson** [comment]
@garretwilson
I have made the requested edits to the BEATBOX-2 branch and updated the repository.
