### ISSUE TITLE
Add hashCode() and equals() methods to Instrument class.

### ISSUE THREAD

**Issue by garretwilson** [salvadore-jefferson/beat_box#8]
If we intend to use `Instrument` in a set or a map, or simply to compare them with each other for whatever reason, we need to override the `hashCode()` and equals()` methods. It's a good idea to do this for all value classes anyway, as you never know how they will be used.

(Get into a habit not just of writing classes for yourself to use in your own program, but imagine some other developer will come along and use your class in some unknown, new project in the future.)

The `Instrument` class can be equal based upon its _number_ (I think you call it _key_ now). It's always a good idea to indicate in the Javadocs what equality of the class is based on.

**Comment by garretwilson** [comment]
I'm not sure... was there ever an `issues/8` branch created for this? It looks like this task was done on branch `issues/9`.

**Comment by salvadore-jefferson** [comment]
Yes, there is an issues/8 branch. I added the hashCode() and equals() methods in that branch, along with a few other changes as I recall. I made the provided corrections to these methods in the issues/9 branch. That's my mistake. We also seem to have skipped issues/7 altogether.

**Comment by garretwilson** [comment]
Actually I had just discovered the `issues/8` branch. But... did you ever do a pull request for it?

**Comment by garretwilson** [comment]
(BTW, GitHub assigns issue numbers, it appears skipping numbers, unfortunately.)

**Comment by salvadore-jefferson** [comment]
Uh oh, no I do not see a pull request for issues/8

Again, my huge mistake. Sorry about that.

**Comment by garretwilson** [comment]
Not every mistake is huge. I'm sure you and I both will make bigger ones in the future. ;)
